# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_video_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(423, 277)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(423, 277))
        Dialog.setMaximumSize(QtCore.QSize(423, 277))
        Dialog.setSizeGripEnabled(False)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label_load_video_name = QtWidgets.QLabel(Dialog)
        self.label_load_video_name.setObjectName("label_load_video_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_load_video_name)
        spacerItem = QtWidgets.QSpacerItem(249, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setEnabled(True)
        self.spinBox.setMaximum(23)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.spinBox_3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_3.setEnabled(True)
        self.spinBox_3.setMaximum(59)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout.addWidget(self.spinBox_3)
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setEnabled(True)
        self.spinBox_2.setMaximum(59)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout.addWidget(self.spinBox_2)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.checkBox)
        self.checkbox_fullscreen = QtWidgets.QCheckBox(Dialog)
        self.checkbox_fullscreen.setChecked(True)
        self.checkbox_fullscreen.setObjectName("checkbox_fullscreen")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.checkbox_fullscreen)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.button_choose_video = QtWidgets.QPushButton(Dialog)
        self.button_choose_video.setObjectName("button_choose_video")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.button_choose_video)
        self.label_load_video_length = QtWidgets.QLabel(Dialog)
        self.label_load_video_length.setObjectName("label_load_video_length")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_load_video_length)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox_4 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_4.setMaximum(6000)
        self.spinBox_4.setSingleStep(60)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.checkBox.toggled['bool'].connect(self.spinBox.setDisabled)
        self.checkBox.toggled['bool'].connect(self.spinBox_3.setDisabled)
        self.checkBox.toggled['bool'].connect(self.spinBox_2.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Load Video"))
        self.label_load_video_name.setText(_translate("Dialog", "<FileName>"))
        self.label_2.setText(_translate("Dialog", "Length:"))
        self.label.setToolTip(_translate("Dialog", "<html><head/><body><p>The absolute time the video starts (ex: 8:31:00) in note format (HH:MM:SS)</p></body></html>"))
        self.label.setText(_translate("Dialog", "Start Time (absolute):"))
        self.spinBox.setSuffix(_translate("Dialog", "h"))
        self.spinBox_3.setSuffix(_translate("Dialog", "m"))
        self.spinBox_2.setSuffix(_translate("Dialog", "s"))
        self.label_4.setText(_translate("Dialog", "Flags:"))
        self.checkBox.setText(_translate("Dialog", "Play Manually"))
        self.checkbox_fullscreen.setText(_translate("Dialog", "Loop"))
        self.button_choose_video.setText(_translate("Dialog", "Change Video"))
        self.label_load_video_length.setText(_translate("Dialog", "<Length>"))
        self.label_3.setToolTip(_translate("Dialog", "<html><head/><body><p>The delay between the END of the last video and the START of this one in seconds.</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Start Time(relative):"))
        self.spinBox_4.setToolTip(_translate("Dialog", "The delay between the END of the last video and the START of this one."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

