# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_load_new_video = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_new_video.setGeometry(QtCore.QRect(10, 10, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_load_new_video.setFont(font)
        self.button_load_new_video.setObjectName("button_load_new_video")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 170, 801, 381))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.title_now_playing = QtWidgets.QLabel(self.centralwidget)
        self.title_now_playing.setGeometry(QtCore.QRect(20, 70, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_now_playing.setFont(font)
        self.title_now_playing.setScaledContents(False)
        self.title_now_playing.setObjectName("title_now_playing")
        self.label_now_playing = QtWidgets.QLabel(self.centralwidget)
        self.label_now_playing.setGeometry(QtCore.QRect(190, 80, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_now_playing.setFont(font)
        self.label_now_playing.setObjectName("label_now_playing")
        self.label_next_playing = QtWidgets.QLabel(self.centralwidget)
        self.label_next_playing.setGeometry(QtCore.QRect(70, 120, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_next_playing.setFont(font)
        self.label_next_playing.setObjectName("label_next_playing")
        self.title_next_playing = QtWidgets.QLabel(self.centralwidget)
        self.title_next_playing.setGeometry(QtCore.QRect(20, 120, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_next_playing.setFont(font)
        self.title_next_playing.setScaledContents(False)
        self.title_next_playing.setObjectName("title_next_playing")
        self.label_now_playing_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_now_playing_2.setGeometry(QtCore.QRect(750, 80, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_now_playing_2.setFont(font)
        self.label_now_playing_2.setObjectName("label_now_playing_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(730, 60, 68, 17))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 23))
        self.menubar.setObjectName("menubar")
        self.menuVideo_Queuer = QtWidgets.QMenu(self.menubar)
        self.menuVideo_Queuer.setObjectName("menuVideo_Queuer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuVideo_Queuer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_load_new_video.setText(_translate("MainWindow", "Load New Video"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Video File"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Length"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start Time"))
        self.title_now_playing.setText(_translate("MainWindow", "Now Playing:"))
        self.label_now_playing.setText(_translate("MainWindow", "<File Name>"))
        self.label_next_playing.setText(_translate("MainWindow", "<File Name>"))
        self.title_next_playing.setText(_translate("MainWindow", "Next:"))
        self.label_now_playing_2.setText(_translate("MainWindow", "2:03"))
        self.label.setText(_translate("MainWindow", "Time left:"))
        self.menuVideo_Queuer.setTitle(_translate("MainWindow", "Video Queuer"))

