# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.loadnew = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadnew.sizePolicy().hasHeightForWidth())
        self.loadnew.setSizePolicy(sizePolicy)
        self.loadnew.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tag-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadnew.setIcon(icon)
        self.loadnew.setIconSize(QtCore.QSize(64, 64))
        self.loadnew.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.loadnew.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.loadnew.setAutoRaise(False)
        self.loadnew.setArrowType(QtCore.Qt.NoArrow)
        self.loadnew.setObjectName("loadnew")
        self.horizontalLayout.addWidget(self.loadnew)
        self.loop = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loop.sizePolicy().hasHeightForWidth())
        self.loop.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("view-refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loop.setIcon(icon1)
        self.loop.setIconSize(QtCore.QSize(64, 64))
        self.loop.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.loop.setObjectName("loop")
        self.horizontalLayout.addWidget(self.loop)
        self.override = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.override.sizePolicy().hasHeightForWidth())
        self.override.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("edit-delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.override.setIcon(icon2)
        self.override.setIconSize(QtCore.QSize(64, 64))
        self.override.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.override.setObjectName("override")
        self.horizontalLayout.addWidget(self.override)
        self.start = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("media-playback-start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon3)
        self.start.setIconSize(QtCore.QSize(64, 64))
        self.start.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.nextPlaying = QtWidgets.QLabel(self.centralwidget)
        self.nextPlaying.setEnabled(True)
        self.nextPlaying.setObjectName("nextPlaying")
        self.verticalLayout.addWidget(self.nextPlaying)
        self.schedtable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedtable.sizePolicy().hasHeightForWidth())
        self.schedtable.setSizePolicy(sizePolicy)
        self.schedtable.setMinimumSize(QtCore.QSize(100, 100))
        self.schedtable.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.schedtable.setStyleSheet("view->horizontalHeader()->setResizeMode(QHeaderView::Stretch)")
        self.schedtable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.schedtable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.schedtable.setDragEnabled(True)
        self.schedtable.setDragDropOverwriteMode(True)
        self.schedtable.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.schedtable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.schedtable.setShowGrid(True)
        self.schedtable.setCornerButtonEnabled(True)
        self.schedtable.setRowCount(15)
        self.schedtable.setColumnCount(3)
        self.schedtable.setObjectName("schedtable")
        item = QtWidgets.QTableWidgetItem()
        self.schedtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedtable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedtable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedtable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedtable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.schedtable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.schedtable.setItem(3, 2, item)
        self.schedtable.horizontalHeader().setVisible(True)
        self.schedtable.horizontalHeader().setCascadingSectionResizes(True)
        self.schedtable.horizontalHeader().setDefaultSectionSize(200)
        self.schedtable.horizontalHeader().setHighlightSections(False)
        self.schedtable.horizontalHeader().setStretchLastSection(True)
        self.schedtable.verticalHeader().setVisible(True)
        self.schedtable.verticalHeader().setHighlightSections(True)
        self.schedtable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.schedtable)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(2, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuVideo_Queuer = QtWidgets.QMenu(self.menuBar)
        self.menuVideo_Queuer.setObjectName("menuVideo_Queuer")
        MainWindow.setMenuBar(self.menuBar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuVideo_Queuer.addAction(self.actionHelp)
        self.menuVideo_Queuer.addAction(self.actionAbout)
        self.menuVideo_Queuer.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuVideo_Queuer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Playing <File Name>"))
        self.loadnew.setText(_translate("MainWindow", "Load New"))
        self.loop.setText(_translate("MainWindow", "Loop"))
        self.override.setText(_translate("MainWindow", "Override"))
        self.start.setText(_translate("MainWindow", "Start Queue"))
        self.nextPlaying.setText(_translate("MainWindow", " Next Playing: <File Name> in 1:10"))
        self.schedtable.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time video will be played. Ex: 8:35:20</p></body></html>"))
        self.schedtable.setSortingEnabled(False)
        item = self.schedtable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Video File"))
        item = self.schedtable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time Video Will Be Played"))
        item = self.schedtable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time In Between Videos"))
        item.setToolTip(_translate("MainWindow", "Leave blank for infinite delay"))
        __sortingEnabled = self.schedtable.isSortingEnabled()
        self.schedtable.setSortingEnabled(False)
        item = self.schedtable.item(0, 0)
        item.setToolTip(_translate("MainWindow", "Video file to play."))
        item = self.schedtable.item(0, 1)
        item.setToolTip(_translate("MainWindow", "Absolute time to play video,"))
        item = self.schedtable.item(0, 2)
        item.setToolTip(_translate("MainWindow", "Time relative to start to play video"))
        self.schedtable.setSortingEnabled(__sortingEnabled)
        self.menuVideo_Queuer.setTitle(_translate("MainWindow", "Video Queuer"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

